"""Public package surface for the standalone :mod:`app_engine` runtime.

The contract types are deliberately imported here, while the executable
server remains opt-in.  In particular, importing ``app_engine`` must not
import the legacy top-level ``engine`` module: that module constructs the
Ollama/model services at import time and is only needed by the launcher.
"""

from .contracts import (
    AppCatalog,
    AppEngineError,
    AppEngineRuntime,
    AppGateway,
    AppId,
    AppManifest,
    AppMetadata,
    AppSession,
    AppSessionId,
    AppSource,
    AppStateStore,
    ApprovalReceipt,
    AssetRequest,
    AssetResponse,
    Authorization,
    AuthorizationError,
    BrowserPolicy,
    CacheStatus,
    CatalogApp,
    CatalogEvent,
    CatalogKey,
    CatalogRejection,
    CatalogSnapshot,
    CommandStep,
    ConfigurationError,
    ConfigurationField,
    ConfigurationForm,
    ConfigurationResult,
    ConfigurationType,
    ConfigurationValue,
    CreateProjectRequest,
    CreatedProject,
    EnvironmentBinding,
    EnvironmentSource,
    HealthCheckError,
    HealthSpec,
    HostAdapter,
    HostCapabilityProviders,
    HostSubject,
    ImportProposal,
    InstanceId,
    LaunchError,
    LaunchHandle,
    LaunchId,
    LaunchPlan,
    LaunchRequest,
    LaunchStatus,
    LifecycleManager,
    LogPage,
    LogRecord,
    ManifestChange,
    ManifestChangePlan,
    ManifestError,
    ManifestInspection,
    OpenAppRequest,
    PlanFingerprint,
    PlannedFile,
    PreparationError,
    PreparedTarget,
    ProcessScope,
    ProjectPlan,
    ProjectTemplate,
    ProxyRequest,
    ProxyResponse,
    ResolvedConfiguration,
    ResolvedStep,
    RuntimeEvent,
    RuntimeFailure,
    RuntimeSpec,
    RuntimeState,
    ScopeKey,
    ScopedCapability,
    ShutdownError,
    ShutdownReport,
    StopReason,
    StopResult,
    StudioRoot,
    StudioService,
    TargetEndpoint,
    TargetEvent,
    TargetId,
    TargetProvider,
    TargetProviderError,
    TargetSession,
    TargetSpec,
    TemplateFile,
    TemplateSummary,
    ToolchainError,
    ToolchainInfo,
    ToolchainInventory,
    ToolchainReport,
    ValidationIssue,
    ValidationReport,
)

__version__ = "0.2.0"

__all__ = [
    "__version__",
    "AppCatalog",
    "AppEngineError",
    "AppEngineRuntime",
    "AppGateway",
    "AppId",
    "AppManifest",
    "AppMetadata",
    "AppSession",
    "AppSessionId",
    "AppSource",
    "AppStateStore",
    "ApprovalReceipt",
    "AssetRequest",
    "AssetResponse",
    "Authorization",
    "AuthorizationError",
    "BrowserPolicy",
    "CacheStatus",
    "CatalogApp",
    "CatalogEvent",
    "CatalogKey",
    "CatalogRejection",
    "CatalogSnapshot",
    "CommandStep",
    "ConfigurationError",
    "ConfigurationField",
    "ConfigurationForm",
    "ConfigurationResult",
    "ConfigurationType",
    "ConfigurationValue",
    "CreateProjectRequest",
    "CreatedProject",
    "EnvironmentBinding",
    "EnvironmentSource",
    "HealthCheckError",
    "HealthSpec",
    "HostAdapter",
    "HostCapabilityProviders",
    "HostSubject",
    "ImportProposal",
    "InstanceId",
    "LaunchError",
    "LaunchHandle",
    "LaunchId",
    "LaunchPlan",
    "LaunchRequest",
    "LaunchStatus",
    "LifecycleManager",
    "LogPage",
    "LogRecord",
    "ManifestChange",
    "ManifestChangePlan",
    "ManifestError",
    "ManifestInspection",
    "OpenAppRequest",
    "PlanFingerprint",
    "PlannedFile",
    "PreparationError",
    "PreparedTarget",
    "ProcessScope",
    "ProjectPlan",
    "ProjectTemplate",
    "ProxyRequest",
    "ProxyResponse",
    "ResolvedConfiguration",
    "ResolvedStep",
    "RuntimeEvent",
    "RuntimeFailure",
    "RuntimeSpec",
    "RuntimeState",
    "ScopeKey",
    "ScopedCapability",
    "ShutdownError",
    "ShutdownReport",
    "StopReason",
    "StopResult",
    "StudioRoot",
    "StudioService",
    "TargetEndpoint",
    "TargetEvent",
    "TargetId",
    "TargetProvider",
    "TargetProviderError",
    "TargetSession",
    "TargetSpec",
    "TemplateFile",
    "TemplateSummary",
    "ToolchainError",
    "ToolchainInfo",
    "ToolchainInventory",
    "ToolchainReport",
    "ValidationIssue",
    "ValidationReport",
]

__all__ += [
    "DefaultAppEngineRuntime",
    "DefaultAppGateway",
    "ImmutableAppCatalog",
    "LocalHostAdapter",
    "PortableStudioService",
    "ProcessLifecycleManager",
    "ProviderRegistry",
    "create_app_engine_router",
]

_LAZY_EXPORTS = {
    "DefaultAppEngineRuntime": (".runtime", "DefaultAppEngineRuntime"),
    "DefaultAppGateway": (".gateway", "DefaultAppGateway"),
    "ImmutableAppCatalog": (".catalog", "ImmutableAppCatalog"),
    "LocalHostAdapter": (".runtime", "LocalHostAdapter"),
    "PortableStudioService": (".studio", "PortableStudioService"),
    "ProcessLifecycleManager": (".lifecycle", "ProcessLifecycleManager"),
    "ProviderRegistry": (".providers", "ProviderRegistry"),
    "create_app_engine_router": (".routes", "create_app_engine_router"),
}


def __getattr__(name: str):
    """Load concrete services only when requested.

    Contract-only imports remain dependency-light, which keeps manifest
    validation usable even in a minimal build environment.
    """
    try:
        module_name, attribute = _LAZY_EXPORTS[name]
    except KeyError:
        raise AttributeError(name) from None
    from importlib import import_module

    value = getattr(import_module(module_name, __name__), attribute)
    globals()[name] = value
    return value
